-- ============================================
-- CIVICPULSE DATABASE SCHEMA
-- ============================================


-- ============================================
-- USERS TABLE
-- ============================================

CREATE TABLE USERS
(
    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    FULL_NAME VARCHAR2(100) NOT NULL,

    EMAIL VARCHAR2(100) UNIQUE NOT NULL,

    USER_PASSWORD VARCHAR2(255) NOT NULL,

    PHONE_NUMBER VARCHAR2(15),

    ROLE VARCHAR2(20)
        DEFAULT 'Citizen'
        CHECK (ROLE IN ('Citizen','Admin','Worker')),

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/


-- ============================================
-- ISSUE CATEGORIES TABLE
-- ============================================

CREATE TABLE ISSUE_CATEGORIES
(
    CATEGORY_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    CATEGORY_NAME VARCHAR2(100) UNIQUE NOT NULL,

    DESCRIPTION VARCHAR2(300),

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/


-- ============================================
-- COMPLAINTS TABLE
-- ============================================

CREATE TABLE COMPLAINTS
(
    COMPLAINT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,


    USER_ID NUMBER NOT NULL,


    CATEGORY_ID NUMBER NOT NULL,


    TITLE VARCHAR2(150) NOT NULL,


    DESCRIPTION VARCHAR2(1000) NOT NULL,


    LOCATION VARCHAR2(255) NOT NULL,


    LATITUDE NUMBER(10,7),


    LONGITUDE NUMBER(10,7),


    STATUS VARCHAR2(20)
        DEFAULT 'Pending'
        CHECK
        (
            STATUS IN
            (
                'Pending',
                'Verified',
                'Assigned',
                'In Progress',
                'Resolved',
                'Rejected'
            )
        ),


    PRIORITY VARCHAR2(10)
        DEFAULT 'Low'
        CHECK
        (
            PRIORITY IN
            (
                'Low',
                'Medium',
                'High'
            )
        ),


    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


    UPDATED_AT TIMESTAMP,


    CONSTRAINT FK_USER_COMPLAINT
        FOREIGN KEY(USER_ID)
        REFERENCES USERS(USER_ID),


    CONSTRAINT FK_CATEGORY_COMPLAINT
        FOREIGN KEY(CATEGORY_ID)
        REFERENCES ISSUE_CATEGORIES(CATEGORY_ID)

);
/