/*=========================================================
  CivicPulse Database Schema
  Database : Oracle
  Day 4
=========================================================*/

----------------------------------------------------------
-- USERS TABLE
----------------------------------------------------------

CREATE TABLE USERS (

    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,

    FULL_NAME VARCHAR2(100) NOT NULL,

    EMAIL VARCHAR2(100) NOT NULL UNIQUE,

    PASSWORD VARCHAR2(255) NOT NULL,

    PHONE_NUMBER VARCHAR2(15),

    ROLE VARCHAR2(20) DEFAULT 'Citizen'
        CHECK (ROLE IN ('Citizen', 'Admin', 'Worker')),

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_USERS
        PRIMARY KEY (USER_ID)

);

----------------------------------------------------------
-- ISSUE CATEGORIES TABLE
----------------------------------------------------------

CREATE TABLE ISSUE_CATEGORIES (

    CATEGORY_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,

    CATEGORY_NAME VARCHAR2(100) NOT NULL UNIQUE,

    DESCRIPTION VARCHAR2(300),

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_CATEGORY
        PRIMARY KEY (CATEGORY_ID)

);

----------------------------------------------------------
-- COMPLAINTS TABLE
----------------------------------------------------------

CREATE TABLE COMPLAINTS (

    COMPLAINT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,

    USER_ID NUMBER NOT NULL,

    CATEGORY_ID NUMBER NOT NULL,

    TITLE VARCHAR2(150) NOT NULL,

    DESCRIPTION VARCHAR2(1000) NOT NULL,

    LOCATION VARCHAR2(255) NOT NULL,

    LATITUDE NUMBER(10,7),

    LONGITUDE NUMBER(10,7),

    STATUS VARCHAR2(20)
        DEFAULT 'Pending'
        CHECK (
            STATUS IN (
                'Pending',
                'Verified',
                'Assigned',
                'In Progress',
                'Resolved',
                'Rejected'
            )
        ),

    PRIORITY VARCHAR2(10)
        DEFAULT 'Low'
        CHECK (
            PRIORITY IN (
                'Low',
                'Medium',
                'High'
            )
        ),

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UPDATED_AT TIMESTAMP,

    CONSTRAINT PK_COMPLAINTS
        PRIMARY KEY (COMPLAINT_ID),

    CONSTRAINT FK_COMPLAINT_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_COMPLAINT_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES ISSUE_CATEGORIES(CATEGORY_ID)

);